### ISSUE TITLE
Versatile damage throwing error in console

### ISSUE THREAD

**Issue by Fayghost** [foundryvtt/dnd5e#3319] opened 2024-03-23 17:05 UTC
![image](https://github.com/foundryvtt/dnd5e/assets/14824185/d448d3a3-7135-4a17-9843-f8b1ad720b20)
When rolling versatile damage from a weapon with the versatile property, the damage does not roll and the console throws an error as per the picture above, please let me know if you would like to have the actual console log file.

**Comment by arbron** [comment] 2024-03-23 17:07
Duplicate of https://github.com/foundryvtt/dnd5e/issues/3306

**Closed by arbron** 2024-03-23 17:07 UTC
Labels: duplicate
