### ISSUE TITLE
Pact Magic doesnt work well in NPCs

### ISSUE THREAD

**Issue by elizeuangelo** [foundryvtt/dnd5e#1642] opened 2022-07-17 13:57 UTC
The only way for an NPC to have pact magic is using the `override` property, but if I dont have any spellcaster level in `data.details.spelllevel` all pact magic slots are always 1st level, if I input a spellcaster level than it upgrades the pact magic slots levels, but it also introduces normal spell slots, making the sheet very poluted with lots of spellcasting spell slots with no purpose. If I override all those spell slots to 0, they still dont disappear.

I believe the best approach would be having separate explicit spellcaster level detail, one for 'normal spellcasting', and another one for 'pact spellcasting'. The rules of the game already treat those differently as pact spellcasters levels dont add/mix with normal spellcasting when defining spell slots in multiclass options. So an NPC could even have normal spellcasting levels + pact spellcasting levels and it would still work properly as intended by multiclass rules.

**Comment by arbron** [comment] 2022-10-24 20:39
Duplicate of #1549

**Closed by arbron** 2022-10-24 20:39 UTC
Labels: duplicate
