### ISSUE TITLE
Bug: SRD monsters on v4.0.4

### ISSUE THREAD

**Issue by Bradeck** [foundryvtt/dnd5e#4609] opened 2024-10-27 09:42 UTC
After upgrading a world from v3.3.1 to v4.0.4, I checked everything. Whenever an SRD actor had some problems, I checked the actor in the compendium, and whenever they also had the errors, I write what I did, so here it is. It may not be the "proper" way to implement the features / activities, but at least it points out the monsters I found that had problems. I'm sorry I don't know how to contribute, otherwise I would have implemented all of this  myself.

# SRD monsters (2014) for Dungeons and Dragons system v4

***All dragons***
- Changed *activity*: `Wing Attack` (legendary action) , damage are wrong almost all wrong, because they use the Dexterity bonus of the Save, instead of the Strength bonus. Added applied Prone condition

***Air Elemental***
- Changed *feature*: `whirlwind`. Damage activity: remove consumption (done by the save feature), Set damage of Damage activity to 1d6
- Added *activity*: `Whirlwind`, Save activity 'flung at creature'

***Bulette***
- Changed *feature*: `Deadly Leap`, removed the Damage activity. Added applied Status Prone to Save activity, rename it Save Str, added a Save Dex activity

***Cloaker***
- Changed *activity*: `Moan`. Save activity: targetint set to emmanation 60 feet. Added Frightened condition as an applied effect.
- Changed *Feature*: `Bite`. Added a Utility activity to add the blind adn suffocating statuses. Added a check feature to detach the cloaker

***Chain Devil***
- Changed *feature*: `Chain`, Replace the Utility activity by a damage activity. Added a check activity to escape the grapple.
- Changed *feature*: `Unnerving Mask`, Removed the Utility activity. Changed the Save activity to apply the frightened condition.

***Couatl***
- Changed *activity*: `Bite` remove damage from the Save activity, added the applied effect Uncounscious.
- Changed *activity*: `Constrict` Attack activity, added the applied effect Grappled.

***Darkmantle***
- Changed *feature*: `Crush`. Removed the Save activity. Added a Attach Utility activity to apply Blinded and Suffocation conditions. Added a Detach Check activity for the target to try and remove the Darkmantle.

***Death Dog***
- Changed *activity*: `Bite`, Remove the damage for the save activity, and add the poisoned and diseased condition instead.

***Deep Gnome***
- Changed *feature*: `Poisoned Dart`. Remove the damage for the save activity, and add the poisoned condition instead.

***Djinni***
- Changed *activity*: `Scimitar`, changed Attack activity, the additional damage can be Lighning or thunder.

***Drider***
- Changed *feature*: `Bite`. Per statblock the bite don't have a +3 bonus (it's 1d4 piercing + 2d8 poison)

***Dust Mephit***
- Changed *feature*: `Blinding Breath`, removed the utility activity, changed the save activity to apply the Blinded condition, set range to self
- Changed *geature*: `Death Burst`, removed the utility activity, changed the save activity to apply the Blinded condition

***Ettercap***
- Changed *feature*: `Bite`. Add an activity for the save against poison
- Fix *feature*: `Web`. Changed the `save` activity for a `Check` activity

***Fire Elemental***
- Changed `Water Susceptibility`. Add a damage activity for 1 cold damage
- Changed *feature*: `Touch`. Changed the Attack activity to give a burning condition. Add a Damage activity for the burning damage.

***Flesh Golem***
- Added *activity*: `Berserk`, addec a check activity to calm it

***Gargoyle***
- Changed *activity*: `Claws`, set the Attack ability to be Str to make the damage 1d6+2

***Gelatinous Cube***
- Changed *feature*: `Engulf`, removed the Utility activity. Added Restrained and Suffocation condition to the Save activity. Added a Damage activity for engulfed creatures. Added a check activity to escape.
- Changed *activity*: `Pseudopod`, reworked the Attack activity to remove the +2 bonus on damage.

***Ghoul***
- Changed *feature*: `Claw`, added Save activity for the paralysis effect.

***Giant Boar***
- Changed *feature*: `Charge`, removed the damage from the save activity, added the applied contition Prone.

***Giant Crocodile***
- Changed *activity*: `Bite`, added the Grappled status as an applied condition
- Changed *activity*: `Tail`, removed damage for the Save activity, and added the Prone status as an applied condition

***Giant Frog***
- Changed *activity*: `Swallow`, the Damage activity should not cost an action.

***Giant Scorpion***
- Changed *activity*: `Claw`, added the `Grappled` status as an applied condition effect to the attack activity
- Changed *feature*: `Sting`, removed the utility activity. Changed the Save activity to apply the poison damage.

***Ghast***
- Changed *feature*: `Claws`, added a Save activity for the paralysis effect.

***Ghoul***
- Changed *feature*: `Claws`. Added a Save activity for the paralysis effect of the attack.

***Ghost***
- Changed *feature*: `Horifying visage`, added the Frightened status as an applied condition to the save activity.
- Changed *feature*: `Possession`, added a possession AE to the save activity

***Gorgon***
- Changed *feature*: `Trampling Charge`, removed the Utility activity. Added the Prone applied effect to the Save activity.
- Changed *activity*: `Petrifying Breath`, added Restrained as an applied condition of the Save activity.

***Imp***
- Changed *activity*: `Bite`, changed the Save activity to add 3d6 poison damage / half on save ; removed the utility activity
- Changed *activity*: `Sting`, changed the Save activity to add 3d6 poison damage / half on save ; removed the utility activity

***Manticore***
- Changed *feature*: `Tail Spike`. Instead of having charge, make it consume its `Tail Spike Regrowth` feature.

***Otyugh***
- Changed *activity*: `Bite`, removed the damage on the Save activity. Added the Diseased & Poisoned applied condition on the Save activity.
- Changed *feature*: `Tentacle Slam`, removed the Attack activity. Added the Stunned applied status to the Save action, and set it's damage bonus to 3.

***Quasit***
- Changed *feature*: `Claw`. Removed the Utility activity. Modified the Save activity to add poison damage and poisoned status.
- Changed *feature*: `Scare`. Removed the Utility activity. Modified the Save activity to add the Frightened condition.

***Remorhaz***
- Added *activity*: on the `Swallow` feature, added a utility activity to add the blinded and restrained conditions

***Rug of Smothering***
- Changed *feature*: `Smother`. Changed the Attack activity to reflect the grappel part of the attack (remove the damage, applies grappled, restrained, blinded and suffocation conditions). Added a damage activity.

***Shadow***
- Changed *Feature*: `Strength Drain`. Add a Utility activity for the Strength Drain roll

***Spirit Naga***
- Changed *feature*: `Bite`. Replaced the piercing damage from the Save activity with the Poison damage from the Attack activity. Removed the poison damage from the Attack activity. 

***Sprite***
- Changed *feature*: `Longsword`. Changed the attack activity to use "none" as an attack ability to reflect the statblock.
- Changed *feature*: `Shortbow`, Changed the attack activity to reflect the statblock. Changed the save activity to remode damage and add the Poisoned status as an applied effect.

***Swarm of Instects, possibly all swarms***
- Fix *feature*: `Bites`. Remove the +1 on it's attack, it's only '4d4 | Pierce'.
- Changed *feature*: `Bites`. Add an attack activity for when the swarm is at half HP or less (2d4 | Pierce)

***Shambling Mound***
- Changed *activity*: `Engulf` save activity. Changed damage bonus to 4, set damage on save to "no damage".
- Added *activity*: `Engulf`, added a Utility activity to add the Blioned, Restrained and Suffocation statuses to the target

***Triceratops***
- Changed *activity*: `Trampling charge`, added the Prone applied condition on the save activity

***Will-o-Wisp***
- Changed *activity*: `Shock`, Attack : the damage are 2d8 | lightning, not 2d8+2.
- Added *activity*: `Consume Life`: added a Heal activity

***Winter Wolf***
- Changed *feature*: `Cold Breath`. Removed the Attack activity.
- Changed *activity*: `Bite`, added Prone as an applied condition for the Save activity.

***Wraith***
- Changed *activity*: `Wraith - Life Drain`, Save activity, remove the damages.

***Wyvern***
- Changed *activity*: `Stinger`, modified the damage of the Save activity to 7d6 Poison.

# SPELLS
***Color Spray***
- Changed *description*: each creature affected by this spell is blinded until the spell ends -> each creature affected by this spell is blinded until the the end of your next turn.
- Delete *activity*: remove the save activity
- Add *activity*: add a utility activity that apply blinded, and make a 6d10 roll.

# ITEMS
***Nine Lives Stealer weapons***
- Changed *activity*: `Save`, remove the damage, add the Dead status.

**Comment by arbron** [comment] 2024-10-28 20:10
Duplicate of https://github.com/foundryvtt/dnd5e/issues/4553

**Closed by arbron** 2024-10-28 20:10 UTC
