### ISSUE TITLE
BUG: Mastery line in Attacks only shown to GM

### ISSUE THREAD

**Issue by asherett** [foundryvtt/dnd5e#4611] opened 2024-10-28 18:12 UTC
When an attack is rolled, the Mastery line with the link to the mastery property is only visible to the GM:
![image](https://github.com/user-attachments/assets/61cdd78f-4e69-4b18-a32e-946fa1ac8d32)
Left image is player view, right image is GM view.

I can see no reason for this to only be visible to the GM, so submitting it as a bug.

Foundry 12.331
dnd5e 4.0.4
only module installed: PHB v 1.2.0

**Comment by arbron** [comment] 2024-10-28 18:44
Duplicate of https://github.com/foundryvtt/dnd5e/issues/4463

**Closed by arbron** 2024-10-28 18:44 UTC
Labels: duplicate
