### ISSUE TITLE
Give option for quick delete of individual chat posts

### ISSUE THREAD

**Issue by GambetTV** [foundryvtt/dnd5e#3549] opened 2024-05-09 22:32 UTC
This is something that Foundry took away way back when, and then added back because a lot of us really missed it, and now DnD has removed again. Please add in the trash can icon to individual posts so that we can quickly delete individual posts with a single click, instead of having to either right click and then click delete, or click the three dots and then click delete. Or at least give us the option. I don't care if it's added in addition to the three dots, or if it replaces it. If it replaces it, we still get all the functionality of it by right clicking on the post.

The reason this is important is because sometimes things go wrong. Not all spells are configured correctly, sometimes a player accidentally targets too many people and suddenly 50 chat messages populate about all the dice rolls you need to take back, etc. etc. For those of us who save our chat logs, we like to keep them tidy. This change triples the time it takes to delete posts, which means I am unlikely to ever bother deleting them again. 

![image](https://github.com/foundryvtt/dnd5e/assets/72000497/b859619c-70a6-4965-96b1-efb89f984a91)

**Comment by arbron** [comment] 2024-05-09 22:48
Duplicate of https://github.com/foundryvtt/dnd5e/issues/3443

**Closed by arbron** 2024-05-09 22:48 UTC
Labels: duplicate
