### ISSUE TITLE
[Request] Organized Advancements

### ISSUE THREAD

**Issue by Kharmans** [foundryvtt/dnd5e#3489] opened 2024-04-23 23:25 UTC
The features we configure on advancements don't have the option to organize alphabeticaly or manual. They just stay there on the position you put they and thats it. If we could organize it, would be great.

**Comment by Fyorl** [comment] 2024-04-25 14:58
Advancement types have a pre-set ordering. But *within* the same type, they should probably be ordered alphabetically if they're not already.

**Comment by arbron** [comment] 2024-04-25 15:26
Advancements are sorted alphabetically, I think this is referring to features within ItemGrant & ItemChoice advancements, in which case it is a duplicate of https://github.com/foundryvtt/dnd5e/issues/2737

**Closed** 2024-05-16 14:51 UTC
Labels: duplicate, ui, feature request, system: advancement
