### ISSUE TITLE
Popping out a chat message and minimizing it leaves a mostly invisible and interactable title bar

### ISSUE THREAD

**Issue by Krigsmaskine** [foundryvtt/dnd5e#4166] opened 2024-09-07 01:01 UTC
Repro steps:
1. Pop out a chat message
2. Double click title bar of popped out message
3. 
[pop out chat message.webm](https://github.com/user-attachments/assets/216be664-c536-4526-ad10-99eae70d2a8f)

**Comment by arbron** [comment] 2024-09-07 19:55
Duplicate of https://github.com/foundryvtt/dnd5e/issues/4088

**Closed by arbron** 2024-09-07 19:55 UTC
