### ISSUE TITLE
[Bug] Item Recharge Formula not sticking.

### ISSUE THREAD

**Issue by ctbritt** [foundryvtt/dnd5e#2396] opened 2023-07-31 16:43 UTC
With all modules off and using Foundry v11.306 and DnD5e 2.2.2, items with charges won't keep the recharge formula on the item sheet. I type it in, close the sheet, have the character take a long rest, and the item recharges. But then, the recharge formula disappears and it won't recharge any more with long rests, unless I input the formula again. This is with both new, fresh items and items that have been in my world for some time. Also created a new test world, and saw same behavior.

**Comment by Fyorl** [comment] 2023-07-31 17:20
Duplicate of #2362

**Closed by Fyorl** 2023-07-31 17:20 UTC
