### ISSUE TITLE
Token Disposition on Summon

### ISSUE THREAD

**Issue by Kharmans** [foundryvtt/dnd5e#3996] opened 2024-08-18 19:13 UTC
When summon a creature, the disposition of the summoned creature could be changed to Friendly, or at least could exist the possibility to change the disposition on Creature Changes in Summoning Configuration.

**Comment by arbron** [comment] 2024-08-18 19:17
Duplicate of https://github.com/foundryvtt/dnd5e/issues/3909

**Closed by arbron** 2024-08-18 19:17 UTC
Labels: duplicate
