### ISSUE TITLE
Support Recharge for New Sheets

### ISSUE THREAD

**Issue by TlMcook** [foundryvtt/dnd5e#3131] opened 2024-02-25 02:33 UTC
The new sheets provide a visual error when encountering Recharge abilities on player sheets (such as with an item that's functionality returns on a roll of 6 on the d6).
![image](https://github.com/foundryvtt/dnd5e/assets/43119444/29f79ca6-a5f5-42ec-9d54-23a46a4ed34f)
displaying **0/** instead of the Charged text, or if expended the roll button.

**Comment by Fyorl** [comment] 2024-02-26 14:02
Duplicate of #2930

**Closed by Fyorl** 2024-02-26 14:02 UTC
