### ISSUE TITLE
Add indicator for Bloodied

### ISSUE THREAD

**Issue by JPMeehan** [foundryvtt/dnd5e#3919] opened 2024-08-01 18:15 UTC
The 2024 Rules Glossary officially defines Bloodied as "A creature is Bloodied while it has half its Hit Points or fewer remaining." It would be helpful if there was a clear indicator on the sheets and/or tokens when a creature is bloodied.

**Comment by krbz999** [comment] 2024-08-01 18:17
Duplicate of #2010 (which has a PR #3876).

**Closed** 2024-08-01 18:48 UTC
