### ISSUE TITLE
Herbalism Kit. Incorrect weight and price

### ISSUE THREAD

**Issue by larumirak** [foundryvtt/dnd5e#1718] opened 2022-08-23 05:16 UTC
The numbers are mixed up. It will be correct: The weight is 3 pounds, and the cost is 5.
https://i.imgur.com/5T9P9be.png

**Comment by kjolern** [comment] 2022-08-23 08:52
can I make this change ?

**Comment by arbron** [comment] 2022-08-24 17:40
Duplicate of #1713

**Closed by arbron** 2022-08-24 17:40 UTC
Labels: duplicate
