### ISSUE TITLE
dnd2.0 function highlightCriticalSuccessFailure bug

### ISSUE THREAD

**Issue by tposney** [foundryvtt/dnd5e#1697] opened 2022-08-14 12:27 UTC
In
```js
function highlightCriticalSuccessFailure(message, html, data) {
  if ( !message.isRoll || !message.isContentVisible || !message.rolls.length ) return;

  // Highlight rolls where the first part is a d20 roll
  const d20Roll = message.rolls.find(r => {
    const d0 = r.dice[0];
    return (d0?.faces === 20) && (d0?.values.length === 1);
  });
  if ( !d20Roll ) return;
  const d = d20Roll.dice[0];

  const isModifiedRoll = ("success" in d.results[0]) || d.options.marginSuccess || d.options.marginFailure;
  if ( isModifiedRoll ) return;

  // Highlight successes and failures
  const critical = d.options.critical || 20;
  const fumble = d.options.fumble || 1;
  if ( d.total >= critical ) html.find(".dice-total").addClass("critical");
  else if ( d.total <= fumble ) html.find(".dice-total").addClass("fumble");
  else if ( d.options.target ) {
    if ( roll.total >= d.options.target ) html.find(".dice-total").addClass("success");
    else html.find(".dice-total").addClass("failure");
  }
}
``` 
The test
```js
    if ( roll.total >= d.options.target ) html.find(".dice-total").addClass("success");
```
throws an error as roll is not defined. If the line is changed to
```js
    if ( d20Roll.total >= d.options.target ) html.find(".dice-total").addClass("success");
```

**Comment by arbron** [comment] 2022-08-18 18:28
Duplicate of #1663 that has been resolved (will be fixed with next alpha)

**Closed by arbron** 2022-08-18 18:28 UTC
Labels: bug, duplicate
