### ISSUE TITLE
[Feature Request] Advancements on other items like features or weapons

### ISSUE THREAD

**Issue by maxobremer** [foundryvtt/dnd5e#3438] opened 2024-04-09 18:51 UTC
It would be nice if you could put advancements on items like features or maybe even weapons.
I see this mostly being useful for feats like Scion of the Outer Planes, Metamagic Adept or Weapon Master, These feats grant items, resistances and/or proficiencies, just like advancements can.

It might also be also be useful for some weapons that have extra actions/options like the Staff of Power that has has Power Strike, Spells and a Retributive Strike. I see this especially usefull/easy to use when combined with #1546 
Maybe if the item has spells that use charges of the weapon, allow that to be set up as well, though the spell bit can be recreated with the module [Items with Spells DnD5e](https://foundryvtt.com/packages/items-with-spells-5e)

**Comment by arbron** [comment] 2024-04-11 17:00
Duplicate of https://github.com/foundryvtt/dnd5e/issues/1524

**Closed by arbron** 2024-04-11 17:00 UTC
Labels: duplicate
