### ISSUE TITLE
Bug:  Weapon Properties Display

### ISSUE THREAD

**Issue by Crowguard** [foundryvtt/dnd5e#1682] opened 2022-08-05 01:25 UTC
![image](https://user-images.githubusercontent.com/99844555/182981854-8a38d66e-679a-4861-b1a0-13806a343610.png)

Ammunition property is displaying incorrectly.

Foundry v10, 3, 277

D&D 5e 02.0.0

No active modules.

**Comment by arbron** [comment] 2022-08-07 20:44
Duplicate of #1569

**Closed by arbron** 2022-08-07 20:44 UTC
Labels: bug, duplicate, ui
