### ISSUE TITLE
Configure resource usage for Hit Dice for non owned items

### ISSUE THREAD

**Issue by maxobremer** [foundryvtt/dnd5e#2099] opened 2023-01-23 23:18 UTC
At the moment when you make an item in the item directory and you want it to use hit dice, you cant set it up to use hit dice properly, you'll have to edit the item after giving it to a player so that it actually uses the lowest or highest hit dice. It would be nice if the option for largest and smallest hit dice were always available.
![image](https://user-images.githubusercontent.com/86924581/214174034-d508a59a-1677-4be4-9ee0-a67347a35440.png)

**Comment by arbron** [comment] 2023-01-25 00:02
Duplicate of #1856

**Closed by arbron** 2023-01-25 00:02 UTC
Labels: duplicate
