### ISSUE TITLE
Error when deleting item that is open in a character sheet

### ISSUE THREAD

**Issue by bluezephyr** [foundryvtt/dnd5e#2152] opened 2023-02-04 15:24 UTC
### What happened?

Using the DnD 5e system

A character sheet was open in the "Inventory" sheet. If an item is opened (i.e., clicked on in order to see some more information) and then deleted, the item is not visually removed from the character sheet. It is, however, actually removed from the character according to the logs. If the character sheet is then closed, it is not possible to open it again unless a reload is done.

An error log is produced.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

- Open a character sheet
- Navigate to the inventory sheet
- Open an item
- Delete the item when it is open

![foundrybug](https://user-images.githubusercontent.com/6703178/216775367-68b1a53f-217b-4453-9ca5-f4f6e6630816.jpg)

### What core version are you reporting this for?

Version 10 build 291

### Relevant log output

```shell
Foundry VTT | Deleted Item with id [sNcSwktAuDKnxoah] in parent Actor [AigV2RroLQXlqHI2]
foundry.js:747 TypeError: An error occurred while rendering ActorSheet5eCharacter 41. Cannot read properties of undefined (reading 'getChatData')
    at ActorSheet5eCharacter.getData (base-sheet.mjs:166:64)
    at ActorSheet5eCharacter.getData (character-sheet.mjs:23:33)
    at ActorSheet5eCharacter._render (foundry.js:5108:29)
    at ActorSheet5eCharacter._render (foundry.js:5822:17)
    at ActorSheet5eCharacter.render (foundry.js:5067:10)
    at ActorSheet5eCharacter.render (foundry.js:6394:18)
    at Actor5e.render (foundry.js:13332:11)
    at Actor5e._onDeleteEmbeddedDocuments (foundry.js:13541:10)
    at Actor5e._onDeleteEmbeddedDocuments (foundry.js:16710:11)
    at ClientDatabaseBackend._handleDeleteEmbeddedDocuments (foundry.js:12983:12)
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by arbron** [comment] 2023-02-05 01:50
Duplicate of #2114

**Closed by arbron** 2023-02-05 01:50 UTC
Labels: bug
