### ISSUE TITLE
The "Prototype Token" link the the character sheet header is broken in version 2.2 

### ISSUE THREAD

**Issue by ShannonMcG** [foundryvtt/dnd5e#2315] opened 2023-05-26 14:59 UTC
After updating to 2.2, nothing happens when I click the "Prototype Token" link in the header bar of the character sheet.

I see this error in the console each time I click the link:

TypeError: An error occurred while rendering TokenConfig 107. Cannot convert undefined or null to object
[Detected 1 package: system:dnd5e]
    at Function.keys (<anonymous>)
    at TokenDocument5e._getTrackedAttributesFromSchema (token.mjs:55:82)
    at TokenDocument5e.getTrackedAttributes (token.mjs:24:67)
    at TokenConfig.getData (foundry.js:70956:53)
    at async TokenConfig._render (foundry.js:5108:18)
    at async TokenConfig._render (foundry.js:5822:5)
onError @ foundry.js:747
🎁call_wrapped @ libWrapper-wrapper.js:507
🎁Hooks.onError#lib-wrapper @ listeners.js:138
🎁Hooks.onError#0 @ libWrapper-wrapper.js:187
(anonymous) @ foundry.js:5069
Promise.catch (async)
render @ foundry.js:5067
render @ foundry.js:70938
_onConfigureToken @ foundry.js:61423
onclick @ foundry.js:61380
(anonymous) @ foundry.js:5239
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2

**Comment by MaxPat931** [comment] 2023-05-26 15:08
Duplicate of recently resolved issue https://github.com/foundryvtt/dnd5e/issues/2295

**Closed** 2023-05-26 15:08 UTC
Labels: duplicate, todelete
