### ISSUE TITLE
Error when creating a new combat encounter

### ISSUE THREAD

**Issue by Ikaguia** [foundryvtt/dnd5e#2474] opened 2023-09-14 16:49 UTC
I get this error when creating a new combat encounter on dnd5e 2.3.1 foundry v11, it could be a dnd5e or core bug, but I believe you guys are better equipped to figure which it is.
![image](https://github.com/foundryvtt/dnd5e/assets/16377028/b2fcd43b-2be3-4a1b-8ab1-f30fd12f544d)

**Comment by Fyorl** [comment] 2023-09-14 17:04
Duplicate of foundryvtt/foundryvtt#9718

**Closed by Fyorl** 2023-09-14 17:04 UTC
