### ISSUE TITLE
Item links aren't committed when the save button is clicked

### ISSUE THREAD

**Issue by TwoCrow** [foundryvtt/dnd5e#2338] opened 2023-06-08 03:09 UTC
![issue](https://github.com/foundryvtt/dnd5e/assets/47902737/fa7d4ea8-edd1-4229-9d80-d19c2a0d8453)

Hopefully that gif loads.

When you drag an item into another item's description to link it, changes are only saved when you close from the item you're editing. If you click the "Save and Close Editor" button, these changes are not saved.

Foundry Version: 11.300
DND5e Version: 2.2.1
I also have no modules installed.

**Comment by krbz999** [comment] 2023-06-08 03:53
I think one key part here is that it is in a compendium.

**Comment by Fyorl** [comment] 2023-07-27 14:08
I wasn't able to reproduce this when I tried, but this was reported quite a while ago, so it's entirely possible that this was a core bug that has since been fixed.

**Comment by Fyorl** [comment] 2023-08-09 11:45
Closing as nonrepro

**Closed by Fyorl** 2023-08-09 11:45 UTC
Labels: bug, nonrepro
