### ISSUE TITLE
Error on load

### ISSUE THREAD

**Issue by bradleyquinn** [foundryvtt/dnd5e#2306] opened 2023-05-26 00:12 UTC
TypeError: Error thrown in hooked function '' for hook 'setup'. Cannot set properties of undefined (setting 'apps')
[Detected 1 package: system:dnd5e]
    at Object.fn (dnd5e.mjs:208:37)
    at #call (foundry.js:724:20)
    at Hooks.callAll (foundry.js:681:17)
    at Game.setupGame (foundry.js:7913:11)
    at Game._initializeGameView (foundry.js:8999:16)
    at Game._initializeView (foundry.js:8975:21)
    at Game.initialize (foundry.js:7825:16)

  | onError | @ | foundry.js:747
-- | -- | -- | --
  | 🎁call_wrapped | @ | libWrapper-wrapper.js:507
  | 🎁Hooks.onError#lib-wrapper | @ | listeners.js:138
  | 🎁Hooks.onError#0 | @ | libWrapper-wrapper.js:187
  | #call | @ | foundry.js:728
  | callAll | @ | foundry.js:681
  | setupGame | @ | foundry.js:7913
  | _initializeGameView | @ | foundry.js:8999
  | _initializeView | @ | foundry.js:8975
  | initialize | @ | foundry.js:7825
  | await in initialize (async) |   |  
  | 🎁call_wrapped | @ | libWrapper-wrapper.js:507
  | 🎁libWrapperInit | @ | libWrapper-api.js:805
  | await in 🎁libWrapperInit (async) |   |  
  | 🎁Game.prototype.initialize#0 | @ | libWrapper-wrapper.js:187
  | window.addEventListener.once | @ | foundry.js:79693

**Comment by Fyorl** [comment] 2023-05-26 12:32
Duplicate of #2297

**Closed by Fyorl** 2023-05-26 12:32 UTC
