### ISSUE TITLE
Starting Equipment Not Being Awarded

### ISSUE THREAD

**Issue by CatchingPhoenix** [foundryvtt/dnd5e#4362] opened 2024-09-20 01:00 UTC
Starting equipment from a background or class is not awarded when added to an actor. Shown are screenshots from the new PHB module, but I have confirmed that new backgrounds and classes do not award the starting equipment either.

I assume this is a dnd5e feature and not a PHB module feature. If it is, I will direct this issue there. 

To reproduce:
- Create a new PC actor.
- Add any background with starting equipment. 

No other modules beyond the PHB compendium module are being used.

![image](https://github.com/user-attachments/assets/c4f7f25b-deac-48ee-8e5b-40297e85af07)

![image](https://github.com/user-attachments/assets/455c9ad8-6ba2-4864-884a-33fdacecc3eb)

![image](https://github.com/user-attachments/assets/5504e94d-994e-4ea5-81f4-7e4f131e4a90)

**Comment by hakr14** [comment] 2024-09-20 03:43
Duplicate of #3381. This is a much nicer ticket though...
My understanding is that this *will* be addressed eventually, just no milestone for it yet.

**Comment by CatchingPhoenix** [comment] 2024-09-20 04:57
> Duplicate of #3381. This is a much nicer ticket though... My understanding is that this _will_ be addressed eventually, just no milestone for it yet.

I don't recall such a neat UI option in the old systems, but I was introduced to Foundry with the Tidy5E already set up, so maybe it was there but disabled. Implementing this should not be too challenging, considering I was doing this with advancements before and WotC is providing new items already set up with starting equipment in the premium modules. It's a QoL feature, but considering how many things are just wrong with the module I paid for, this was one more thing that was undoubtedly intended and partially implemented but not complete. Since I'm making a level 20 character for every subclass this week, it would be very nice to have the equipment there so my players and I don't need to worry about it.

**Comment by Fyorl** [comment] 2024-10-03 19:24
Closing in favour of #3381

**Closed by Fyorl** 2024-10-03 19:24 UTC
