### ISSUE TITLE
Character Sheet "Favorites" only shows a maximum of 2 digits for variable use items

### ISSUE THREAD

**Issue by schnoodly** [foundryvtt/dnd5e#3160] opened 2024-03-01 02:41 UTC
![image](https://github.com/foundryvtt/dnd5e/assets/20142693/0655962d-75cc-4f54-8d27-76fe9a3c5501)

When you add an item with three or more digit uses, the first part (variable amount) only shows the first two digits. It would be nice if it showed more, and have an ellipsis for larger numbers.

**Comment by Fyorl** [comment] 2024-03-01 12:42
That doesn't look right, it should be rendered with the `.uses-sm` class.

**Comment by arbron** [comment] 2024-03-01 17:50
Duplicate of https://github.com/foundryvtt/dnd5e/issues/3088, which will be solved once `3.0.4` is released

**Closed by arbron** 2024-03-01 17:50 UTC
Labels: bug, duplicate, ui
