### ISSUE TITLE
Deleting an expanded sheet item bricks sheet until page is reloaded

### ISSUE THREAD

**Issue by TheGiddyLimit** [foundryvtt/dnd5e#2174] opened 2023-02-09 19:22 UTC
A sheet item ID is not removed from the sheet's `_expanded` set when the item is deleted, and thus the iteration -> `get` -> `call method on...` [here](https://github.com/foundryvtt/dnd5e/blob/master/module/applications/actor/base-sheet.mjs#L166) throws an error. This prevents any subsequent re-rendering of the sheet until the page is reloaded.

Repro:

```js
(async () => {
	const act = await Actor.create({name: "Test", type: "character"});
	const itemsCreated = await act.createEmbeddedDocuments("Item", [{name: "Sheet Item", type: "loot"}]);
	Hooks.once("renderActorSheet", async () => {
		act.sheet._tabs[0].activate("inventory");
		$(act.sheet._tabs[0]._content).find(".item-name h4").click();
		await act.deleteEmbeddedDocuments("Item", itemsCreated.map(it => it.id));
	})
	act.sheet.render(true);
})()
```

**Comment by Fyorl** [comment] 2023-02-09 19:42
Duplicate of #2114

**Closed by Fyorl** 2023-02-09 19:42 UTC
