### ISSUE TITLE
Actor sheet re-renders cause any expanded item descriptions to collapse

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/dnd5e#2083] opened 2023-01-20 13:28 UTC
Originally reported by Mark#7040 https://discord.com/channels/170995199584108546/956306859491471420/1065273052516065392

**ALL MODULES DISABLED?:** True  
**OS, Hosting, Browser (if applicable):** Windows 10, Electron self-host (release 291, D&D5e V10 compatible versions), chrome (player side)  
**Short Description of bug:** Item/feature/spell/etc. that is selected to view detail text collapses when the combat tracker is advanced if the actor is in the encounter and any effect is present on their sheet.  
**Simple steps to reproduce the bug:** Create an actor with any effect in the effects tab (temp/active/inactive), add/create item with detail text such that clicking the item expands the line to show text, drag token to map/add to combat encounter/begin combat, select new round/next turn while actor sheet is open and the item is expanded to view text.   
**Screenshots and/or console errors:** no console errors or messages.

**Comment by krbz999** [comment] 2023-01-20 16:08
Related: <https://github.com/foundryvtt/dnd5e/issues/244>

**Comment by arbron** [comment] 2023-01-21 00:11
Closing this as it is a duplicate of #244

**Closed by arbron** 2023-01-21 00:11 UTC
Labels: duplicate
