### ISSUE TITLE
(V10) Unable to expand item summary

### ISSUE THREAD

**Issue by Terked** [foundryvtt/dnd5e#1699] opened 2022-08-14 14:47 UTC
**Summary**
User is unable to expand any item, feature or spell summary when done through the actor sheet

**Steps to reproduce**
1. Open an actor sheet _(can be adventurer or NPC)_
2. Navigate to an item
3. Click on item to expand item summary
4. Observe nothing happening. Console error thrown
  _Expected_: Item summary expands

**Other info**
- All modules disabled
- **Foundry version:** V10 testing 3
- **System version:** DnD5e - Fifth Edition System 2.0.0-alpha2
- **Platform**: Chrome Version 104.0.5112.79 (Official Build) (x86_64)
- **Reproduced on sheets**: Default 5e NPC Sheet, Default 5e Adventurer Sheet 

**Console error**
```
dnd5e.mjs:11639 Uncaught TypeError: Cannot read properties of undefined (reading 'value')
    at ActorSheet5eNPC._onItemSummary (dnd5e.mjs:11639:69)
    at HTMLHeadingElement.<anonymous> (dnd5e.mjs:11215:67)
    at HTMLHeadingElement.dispatch (jquery.min.js:2:43064)
    at v.handle (jquery.min.js:2:41048)
_onItemSummary @ dnd5e.mjs:11639
(anonymous) @ dnd5e.mjs:11215
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
```

**Comment by Keltis456** [comment] 2022-08-14 20:37
Can be fixed by making `_onItemSummary(event)` async. Bug caused by not awaiting `const chatData = item.getChatData({secrets: this.actor.isOwner});`

**Comment by Keltis456** [comment] 2022-08-14 20:41
From what I see it already should be fixed by https://github.com/foundryvtt/dnd5e/issues/1660

**Comment by arbron** [comment] 2022-08-16 23:30
Already fixed

**Closed by arbron** 2022-08-16 23:30 UTC
Labels: bug, duplicate
