### ISSUE TITLE
Containers bypass identification

### ISSUE THREAD

**Issue by gbgitch** [foundryvtt/dnd5e#3015] opened 2024-02-11 02:08 UTC
With 3.0.1 unidentified items in containers have the identified description in the expanding text, looks like you need to be an observer to get the unidentified text in the pop out window

**Comment by arbron** [comment] 2024-02-12 18:00
Duplicate of https://github.com/foundryvtt/dnd5e/issues/2993

**Closed by arbron** 2024-02-12 18:00 UTC
Labels: duplicate
