### ISSUE TITLE
add the recharge button to the new PC sheets

### ISSUE THREAD

**Issue by Ara0n** [foundryvtt/dnd5e#3187] opened 2024-03-05 08:26 UTC
The old legacy sheets allowed you to roll for a recharge (for `recharge 5-6` style features) at the click of a button.
The new sheet lost this features and instead always displays `0/` in the uses column.

**Comment by TheJetarR** [comment] 2024-03-05 13:51
It sort of does have a text button if you set the actor up correctly:
![image](https://github.com/foundryvtt/dnd5e/assets/162299489/1c46a828-a78b-494f-8bc2-510cbe560df6)

It's a hassle on homemade monsters, but for Beyond imports and SRDs you just click the text it will roll for recharge.

**Comment by krbz999** [comment] 2024-03-05 13:56
> It's a hassle on homemade monsters, but for Beyond imports and SRDs you just click the text it will roll for recharge.

This issue is about the new character sheet added in v3.0.0, not NPC sheets. Also: #2930

**Comment by TheJetarR** [comment] 2024-03-05 14:03
@krbz999  Indeed, that was my bad, sorry about that.

**Comment by Fyorl** [comment] 2024-03-05 14:07
Duplicate of #2930

**Closed by Fyorl** 2024-03-05 14:07 UTC
