### ISSUE TITLE
Issue with Background and choices for any level

### ISSUE THREAD

**Issue by etoy22** [foundryvtt/dnd5e#2391] opened 2023-07-28 15:39 UTC
hey getting an issue after trying to make a choice upgrade for a background. I already made a choice feature and now it doesn't show up and if I try to make another one the error occurs. I think the issue is the at any level as I made a new choice option on a different background it disappears only when I put in a value for at any level
![Screenshot 2023-07-28 113946](https://github.com/foundryvtt/dnd5e/assets/20910516/3e80729e-0a65-4274-a582-16d9f3a45d1f)
![Screenshot 2023-07-28 113924](https://github.com/foundryvtt/dnd5e/assets/20910516/9e054656-9ad4-4f11-a457-97a3bad5f68b)

**Comment by etoy22** [comment] 2023-07-28 15:41
It completely is gone when it's only choose item at any level. It still shows up if there is a number in any level and a different level

**Comment by Fyorl** [comment] 2023-07-28 15:58
Duplicate of #2339

**Closed by Fyorl** 2023-07-28 15:58 UTC
