### ISSUE TITLE
(bug) Source picker not working in non player character sheets

### ISSUE THREAD

**Issue by DragonHale** [foundryvtt/dnd5e#4263] opened 2024-09-16 05:09 UTC
When trying to define a source for a npc, the sheet will return an empty field after saving. If I open the source dialogue again after saving, it will show as an empty field even though it was previously filled and saved.

If the monster had a source before migration, it will not allow me to change it or empty it. It will remain with the source it had before migration no matter how many times I save it to change or empty it.

The page fields seem to work just fine. This is just for the source book, it seems, and only for npcs (items seem to be working normally). There are no errors in the console and I'm only working with my shared compendia. No other modules.

![image](https://github.com/user-attachments/assets/e080e518-dd12-4fd0-81f1-e14d7c5c8aac)
![image](https://github.com/user-attachments/assets/34cd4877-e8b9-4e4f-a9c1-d7361252ca78)
![image](https://github.com/user-attachments/assets/0937b953-fd46-45e8-8e46-76b7017f6a98)

**Comment by arbron** [comment] 2024-09-16 05:18
Duplicate of https://github.com/foundryvtt/dnd5e/issues/4251

**Closed by arbron** 2024-09-16 05:18 UTC
Labels: duplicate
