### ISSUE TITLE
Prepared Spells issue on new D&D5e character sheet

### ISSUE THREAD

**Issue by rtschaefer** [foundryvtt/dnd5e#3212] opened 2024-03-08 01:01 UTC
The new character sheet does not seem to track/display how many spells the character has prepared, and just as important, how many preparation slots are remaining. As a result, most of the players are reverting back to Tidy Sheet. I would like to remove that module and stick to the new sheet, but this feature is rather important to them. Perhaps not a bug report, but a major oversight for a standard feature expectation.

**Comment by Fyorl** [comment] 2024-03-08 14:26
Duplicate of #2978

**Closed by Fyorl** 2024-03-08 14:26 UTC
