### ISSUE TITLE
denim075.png and the icon used for 'Humanoid' error with a routePrefix

### ISSUE THREAD

**Issue by etiquettestartshere** [foundryvtt/dnd5e#3575] opened 2024-05-16 14:54 UTC
Steps to reproduce: set a route prefix in options.json such as 
```json
  "routePrefix": "test",
```
then connect to a dnd5e foundry world and open a character sheet, preferably a humanoid actor like Morthos (Tiefling Sorcerer). The denim background texture and that icon (at least) fail to load. The fix would seem to be using relative filepaths for those images, and any others that may have this issue.

![image](https://github.com/foundryvtt/dnd5e/assets/148253744/defd7ef9-3ba3-4dc4-b863-856e0cf1be3b)
![image](https://github.com/foundryvtt/dnd5e/assets/148253744/00610865-35ae-4723-b523-c442577f228e)

Results obtained on foundry version 11.315, dnd5e 3.1.2 and a (slightly old) 3.2, no modules enabled

**Comment by Fyorl** [comment] 2024-05-16 15:55
Duplicate of #3441

**Closed by Fyorl** 2024-05-16 15:55 UTC
