### ISSUE TITLE
Deleting expanded items in inventory freezes actor sheet until refresh

### ISSUE THREAD

**Issue by ForbiddenArcana** [foundryvtt/dnd5e#2183] opened 2023-02-11 19:29 UTC
Every time I delete an item on a PC or NPC character sheet while its description is expanded, the sheet locks up. The delete does take effect but it's not shown visually, and any other resource usages or quantities that are changed also aren't shown visually, though features/items/checks can still be used/rolled from the sheet. If the sheet is closed, it can't be reopened at all. All of these issues clear upon refreshing/reconnecting, but until that is done the sheet is unusable. Everything functions as expected for items that are deleted while collapsed.

Foundry 10.291
dnd5e 2.1.4, character sheets created on this version
No modules activated
Self-hosted on Windows using NodeJS 16.15.0

Console error

```javascript
foundry.js:747 
        
       TypeError: An error occurred while rendering ActorSheet5eCharacter 42. Cannot read properties of undefined (reading 'getChatData')
    at ActorSheet5eCharacter.getData (base-sheet.mjs:166:64)
    at ActorSheet5eCharacter.getData (character-sheet.mjs:23:33)
    at ActorSheet5eCharacter._render (foundry.js:5108:29)
    at ActorSheet5eCharacter._render (foundry.js:5822:17)
    at ActorSheet5eCharacter.render (foundry.js:5067:10)
    at ActorSheet5eCharacter.render (foundry.js:6394:18)
    at Actor5e.render (foundry.js:13332:11)
    at Actor5e._onDeleteEmbeddedDocuments (foundry.js:13541:10)
    at Actor5e._onDeleteEmbeddedDocuments (foundry.js:16710:11)
    at ClientDatabaseBackend._handleDeleteEmbeddedDocuments (foundry.js:12983:12)
onError @ foundry.js:747
(anonymous) @ foundry.js:5069
Promise.catch (async)
render @ foundry.js:5067
render @ foundry.js:6394
render @ foundry.js:13332
_onDeleteEmbeddedDocuments @ foundry.js:13541
_onDeleteEmbeddedDocuments @ foundry.js:16710
_handleDeleteEmbeddedDocuments @ foundry.js:12983
_deleteEmbeddedDocuments @ foundry.js:12886
await in _deleteEmbeddedDocuments (async)
delete @ commons.js:6856
await in delete (async)
deleteDocuments @ commons.js:6198
delete @ commons.js:6265
callback @ foundry.js:56465
button.callback @ foundry.js:56516
submit @ foundry.js:56403
_onClickButton @ foundry.js:56332
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
```

**Comment by MaxPat931** [comment] 2023-02-11 19:30
Duplicate of https://github.com/foundryvtt/dnd5e/issues/2114

**Closed** 2023-07-11 20:06 UTC
Labels: duplicate, todelete
