### ISSUE TITLE
Enchanting an item with system.attunement required makes you unable to attune to the item

### ISSUE THREAD

**Issue by Krigsmaskine** [foundryvtt/dnd5e#3633] opened 2024-05-26 23:14 UTC
Enchanting an item with `system.attunement | override | required` makes you unable to manually attune to the item, the actor sheet gets the attunement shortcut button but it's defunct and the attunement checkbox can be saved but does not save.

**Comment by arbron** [comment] 2024-05-27 18:54
Duplicate of https://github.com/foundryvtt/dnd5e/issues/3616

**Closed by arbron** 2024-05-27 18:54 UTC
Labels: duplicate
