### ISSUE TITLE
Expose default compendiums to the `CONFIG.DND5E`

### ISSUE THREAD

**Issue by phenomen** [foundryvtt/dnd5e#2826] opened 2024-02-02 00:26 UTC
Right now, compendiums that are opened with **Add Class/Race/Background** buttons are hardcoded in the `_onFindItem` function. It would be great if those things were set in the `CONFIG.DND5E` instead. So that modules (Ruins of Symbaroum, Everyday Heroes, Valda's Spire of Secrets and even future official content like 5e PHB) would be able to set their own default compendiums instead of opening SRD ones.

https://github.com/foundryvtt/dnd5e/blob/624393b94984dd719b41bb8ed1456da369d48bf2/module/applications/actor/character-sheet-2.mjs#L878-L889

**Comment by arbron** [comment] 2024-02-02 00:45
Duplicate of https://github.com/foundryvtt/dnd5e/issues/2780

**Closed by arbron** 2024-02-02 00:45 UTC
Labels: duplicate
