### ISSUE TITLE
Allow granting proficiencies, senses, traits etc as an option to character advancement

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#1523] opened 2022-05-03 15:39 UTC
Originally in GitLab by @maxobremer

It would be nice if adding a class, subclass, background (possible race item later down the line) would also add the appropriate proficiencies to the character.

other things that could be added are damage resistances, condition immunities and darkvision as examples

**Comment by arbron** [comment] 2023-11-07 04:12
Duplicate of #1405

**Closed by arbron** 2023-11-07 04:12 UTC
Labels: duplicate
