### ISSUE TITLE
Polymorphing does not revert correctly for NPC Actors

### ISSUE THREAD

**Issue by revilowaldow** [foundryvtt/dnd5e#1917] opened 2022-11-02 20:46 UTC
Reproduction Steps:
- Copy Bandit and Mammoth from dnd5e srd compendium
- Drag Bandit onto canvas
- Drag Mammoth onto Bandit Sheet
- Observe new Bandit (Mammoth) Sheet does not a have a revert button
- Reopen the sheet and use the new button to revert
- Observe that the button initially reverts the token size but nothing else seems to change.
- No errors are thrown though there are some deprecation warnings

https://user-images.githubusercontent.com/52298102/199598461-bf687403-b9b5-4762-afb5-d5f28e7db13f.mp4

Comparison: Original Bandit Vs 'Reverted' Bandit
![image](https://user-images.githubusercontent.com/52298102/199598999-ae6d9618-b0c1-49c2-b756-e147d699f0e6.png)

**Comment by Fyorl** [comment] 2022-11-18 15:58
Duplicate of #1823

**Closed by Fyorl** 2022-11-18 15:58 UTC
