### ISSUE TITLE
Add display of number of prepared spells back to spellbook

### ISSUE THREAD

**Issue by flyingsquad** [foundryvtt/dnd5e#2978] opened 2024-02-08 18:58 UTC
The old character sheet displayed the number of prepared spells in the header. This number is no longer shown in the new character sheet.
This was useful for wizards and clerics, who can know any number of spells, but only have access to a limited number of them at one time, dictated by level and ability modifier.
As a bonus feature, which would require significantly more work, it would be great if this count was separate for each class. That is, a multiclassed cleric/wizard would have two prepared skill counts. That means that each spell in the list would need to be qualified as wizard or cleric. This is easy for spells that only one class has access to (magic missile and cure wounds, for example), but would require the user to select a class for spells that both classes have access to, like detect magic, or wizard spells that certain cleric domains have access to.

**Comment by laaruk** [comment] 2024-02-10 11:53
I second the motion!

**Comment by justinthejaguar** [comment] 2024-02-19 02:23
I and my players third this.

**Comment by Lwftmb** [comment] 2024-03-02 14:17
I believe every user/group would appreciate adding these already foundry-tracked values to the pc sheet.

**Comment by gitscosh** [comment] 2024-03-18 13:57
Indeed. I came here looking for this exact thing. I don't want to have to do math every time I need to double check that I have the right amount of spells prepared. I like the display on Tidy. Should be easy to add it to the new sheets. BTW, the new sheets are SWEET otherwise. Really like them!

**Comment by TheDSeraph** [comment] 2024-03-21 22:00
Yeah it would be really great to have this as its a pretty key thing to track for some spellcasters.
Displaying the # of your prepared spells / # of your max prepared spells on the new character sheet would go a long way to allowing everyone to equally use and enjoy it.

**Comment by Padhiver** [comment] 2024-03-23 07:18
All the same, if it could ever be possible, maybe next to Spellcasting, there's room. :)

**Comment by arbron** [comment] 2024-04-08 16:03
Keeping this open for now for reference, but duplicate of https://github.com/foundryvtt/dnd5e/issues/1021

**Closed** 2024-08-27 13:28 UTC
Labels: ui, feature request, ux
