### ISSUE TITLE
Exhaustion Speed Reduction Incorrectly Calculated in Metric System (and maybe other effects)

### ISSUE THREAD

**Issue by seb9393** [foundryvtt/dnd5e#4869] opened 2024-12-12 20:17 UTC
Hi,

I noticed a problem when using the metric system for character sheets. Some automation features, such as exhaustion effects, appear to be incorrect. For example, at Exhaustion Level 1, a character's speed should be reduced by an amount proportional to 5 feet multiplied by the exhaustion level.

When using the metric system, this reduction should instead be 1.5 meters per exhaustion level. However, the system currently reduces speed by 5 meters per exhaustion level, as if it is still using feet for the calculation but incorrectly applying it to the speed in meters.

This behavior results in an excessive reduction in speed when the metric system is used determining the character speed.

Could you please look into this issue?

Thank you!

**Comment by arbron** [comment] 2024-12-12 20:22
Duplicate of https://github.com/foundryvtt/dnd5e/issues/4215

**Closed by arbron** 2024-12-12 20:22 UTC
Labels: duplicate
