### ISSUE TITLE
Multi-atack items

### ISSUE THREAD

**Issue by 6elkir** [foundryvtt/dnd5e#2862] opened 2024-02-03 13:25 UTC
Please add the ability to create objects with several separate attacks (as in pf1): this is a very necessary opportunity to implement, for example, an ax with a point on one side and a flat head on the other plus a blow with the handle. We've been waiting for this feature for a long time!

**Comment by strannik469** [comment] 2024-02-03 13:46
Yep, this feature is really important, make it please. Know it due to using this exact type of weapon)

**Comment by arbron** [comment] 2024-02-03 19:32
Duplicate of https://github.com/foundryvtt/dnd5e/issues/461, which is more specifically going to be handled by some variant of this: https://github.com/foundryvtt/dnd5e/issues/1964

**Closed** 2024-02-03 19:32 UTC
Labels: duplicate
