### ISSUE TITLE
Unable to open Krusk's sheet from the compendium.

### ISSUE THREAD

**Issue by Padhiver** [foundryvtt/dnd5e#3675] opened 2024-05-31 14:17 UTC
Title.
But if you import it, then you can open it.

No module and version : 

- D&D 3.2
- Foundry 12.325

Error : 
![image](https://github.com/foundryvtt/dnd5e/assets/80126915/14c4a474-8b25-44a2-9df4-80ed005ef48f)

**Comment by roth-michael** [comment] 2024-05-31 14:31
Specifically, this seems to be an issue in V12 with `fromUuidSync` - the reason it's only Krusk is because they're the only starter hero with a favorite set. Can reproduce the same error by creating an actor in a compendium and trying to assign it a favorite. Here's the relevant V12 code in `fromUuidSync` that throws the error - not sure whether this can be avoided on the 5e side of things:
```js
if ( (collection instanceof CompendiumCollection) && embedded.length ) {
  if ( !strict ) return null;
  throw new Error(
    `fromUuidSync was invoked on UUID '${uuid}' which references an Embedded Document and cannot be retrieved `
    + "synchronously.");
}
  ```

**Comment by thatlonelybugbear** [comment] 2024-05-31 14:55
<https://github.com/foundryvtt/dnd5e/blob/eef7cde5164abf7d51772850f15253799ed389b4/module/applications/actor/character-sheet-2.mjs#L1235>

Seems that changing the `fromUuidSync()` to `await fromUuid()` resolves this

**Closed** 2024-05-31 20:18 UTC
Labels: bug
