### ISSUE TITLE
Context Menus go off screen when at the bottom of the character sheet

### ISSUE THREAD

**Issue by LadyDefile** [foundryvtt/dnd5e#2956] opened 2024-02-07 16:14 UTC
![image](https://github.com/foundryvtt/dnd5e/assets/67084868/2665427c-2b0d-4857-9fbf-0974c33ce94b)
Exactly as the image shows here.
The only "solution" is to shrink the sheet and then you can see it.
![image](https://github.com/foundryvtt/dnd5e/assets/67084868/4fc751e7-9e7d-4480-b5e2-5e657e449312)

**Comment by Fyorl** [comment] 2024-02-07 16:22
Duplicate of #2876

**Closed by Fyorl** 2024-02-07 16:22 UTC
