### ISSUE TITLE
(Feature Request) Add a race and a subrace items

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#1568] opened 2022-05-27 04:54 UTC
Originally in GitLab by @dragonhale

This is basically the same as the #342 request, but adding a subrace item type too, not just a race item type, and adding a level advancement integration as well.

Similar as how the class and subclass items work in conjunction, there should be a race and a subrace items. That way you can get racial features from your race and subrace automatically when you drag it into your character sheet and you can even get new racial features when you level up (for example the spells you get at first, third, and fifth level for Tiefling and the feature you get at third level for aasimar).This would be similar to the advancement granted by the class and subclass items.

**Comment by LiamFallon213** [comment] 2022-10-12 21:26
I would also like this, I don't know 100% but I'd assume this could be done with an inherited object on the back end.

**Comment by arbron** [comment] 2022-10-24 20:38
Duplicate of #342

**Closed by arbron** 2022-10-24 20:38 UTC
