### ISSUE TITLE
Add information about group actors on the wiki

### ISSUE THREAD

**Issue by maxobremer** [foundryvtt/dnd5e#3332] opened 2024-03-24 00:28 UTC
For some people there is some confusion on how group actors work or how to set the primary party. Maybe an addition on the wiki can resolve this confusion so people can make use of group actors more and understand what it can and cant do.

A lot can probably be copied from the [v3 release page](https://github.com/foundryvtt/dnd5e/releases/tag/release-3.0.0#user-content-group-actors), but that isn't a clear place to go looking for that information, the wiki is.

**Comment by arbron** [comment] 2024-03-24 01:15
Duplicate of https://github.com/foundryvtt/dnd5e/issues/2828

**Closed by arbron** 2024-03-24 01:15 UTC
Labels: duplicate
