### ISSUE TITLE
Add Subclass Option advancement Type

### ISSUE THREAD

**Issue by Zanderaf** [foundryvtt/dnd5e#2308] opened 2023-05-26 01:45 UTC
A subclass option advancement type could help create a more streamlined character building and level up experience if a class could include a list of subclass options as an advancement type for the player to choose from at an appropriate level.

**Comment by kaelad02** [comment] 2023-05-26 07:06
duplicate of #1407

**Closed** 2023-05-26 15:31 UTC
Labels: duplicate
