### ISSUE TITLE
Global Foundry font size slider interacts poorly with 3.0.3 character sheets.

### ISSUE THREAD

**Issue by UmbralAlderman** [foundryvtt/dnd5e#3170] opened 2024-03-02 05:06 UTC
Some of the fonts scale, some done, much of the layout has at least minor functionality issues.

**Comment by arbron** [comment] 2024-03-02 20:33
Duplicate of https://github.com/foundryvtt/dnd5e/issues/3058

**Closed by arbron** 2024-03-02 20:33 UTC
Labels: duplicate
