### ISSUE TITLE
Consider adding min-width and min-height to compendium browser

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/dnd5e#4449] opened 2024-09-27 16:28 UTC
![image](https://github.com/user-attachments/assets/cd48aaf5-c2c6-491c-85ef-7140c29c2d1b)

**Comment by arbron** [comment] 2024-09-27 17:17
Duplicate of https://github.com/foundryvtt/dnd5e/issues/3843

**Closed by arbron** 2024-09-27 17:17 UTC
Labels: duplicate
