### ISSUE TITLE
[4.1] Bug: Initiative not being rolled properly at advantage - Feral instinct

### ISSUE THREAD

**Issue by thystra** [foundryvtt/dnd5e#4690] opened 2024-11-10 18:07 UTC
From this issue: https://github.com/foundryvtt/dnd5e/issues/4684
 DND 4.1.0
Foundry 12.331

Separating out the advantage issue

When the PC Barbarian was rolling at advantage, Foundry would show that it was supposed to be at advantage, but only one die would roll and show up in the chat log. 

![Screenshot From 2024-11-09 20-25-24](https://github.com/user-attachments/assets/c78beb80-9bf5-40c6-8161-4e2d9eaf9ac0)

![Screenshot From 2024-11-09 20-36-36](https://github.com/user-attachments/assets/4f8c0e82-4cce-44c2-bc44-2d1d4eaf3326)

Active modules:
![Screenshot From 2024-11-09 20-29-20](https://github.com/user-attachments/assets/ac329cef-d2b3-4a57-b1ff-d07f9306b15f)

**Comment by M0nk3yy** [comment] 2024-11-10 19:40
The system does not automate any Advantage or Disadvantage. However the following behaviours appear to be bugged:

1. The `Advantage on Initiative` box, if checked, should highlight `Advantage` in the roll dialog. This does not appear to be happening.

2. Manually clicking `Advantage` in the roll dialog displays `2d20kh` in the chat but only rolls a single die. This occurs regardless of whether the Advantage box is ticked or not.

Presumably these bugs were introduced with the 4.1 roll refactor.

**Comment by arbron** [comment] 2024-11-11 00:32
Duplicate of https://github.com/foundryvtt/dnd5e/issues/4679

**Closed by arbron** 2024-11-11 00:32 UTC
Labels: duplicate
