### ISSUE TITLE
'Add Class' button opens the 'class features', instead of 'classes' compendium

### ISSUE THREAD

**Issue by Ikaguia** [foundryvtt/dnd5e#2816] opened 2024-02-01 18:35 UTC
![image](https://github.com/foundryvtt/dnd5e/assets/16377028/97d390b7-46ac-4998-ad7b-58eb15fb4dcb)

**Comment by arbron** [comment] 2024-02-01 19:17
Duplicate of https://github.com/foundryvtt/dnd5e/issues/2764

**Closed by arbron** 2024-02-01 19:17 UTC
Labels: duplicate
